# This rule is not used by the project kubes3 itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the aws.nullzen.ai.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubes3
    app.kubernetes.io/managed-by: kustomize
  name: s3bucket-editor-role
rules:
- apiGroups:
  - aws.nullzen.ai
  resources:
  - s3buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.nullzen.ai
  resources:
  - s3buckets/status
  verbs:
  - get
