apiVersion: aws.nullzen.ai/v1
kind: S3Bucket
metadata:
  labels:
    app.kubernetes.io/name: kubes3
    app.kubernetes.io/managed-by: kustomize
  name: s3bucket-sample
spec:
  # TODO(user): Add fields here
